# Generated by Django 3.0.1 on 2020-01-03 20:14

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('image', models.ImageField(upload_to='authors', verbose_name='Фотография автора')),
                ('description', models.TextField(verbose_name='Должность/регалии автора')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='headings', verbose_name='Изображеие')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('publication_date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('short_text', models.TextField(verbose_name='Короткий текст для описания')),
                ('text', djrichtextfield.models.RichTextField(verbose_name='Текст статьи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Headings.Author', verbose_name='Автор')),
            ],
        ),
    ]
