version: '3.7'

services:
  web:
    build: ./ChinaBack
    command: gunicorn ChinaBack.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./ChinaBack/:/usr/src/ChinaBack/
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
