version: '3.3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/ChinaBack/staticfiles
      - static_volume:/usr/src/ChinaBack/mediafiles
      - frontend_volume:/usr/src/ChinaBack/frontend
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: ./ChinaBack
      dockerfile: Dockerfile.prod
    command: gunicorn ChinaBack.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/ChinaBack/staticfiles
      - static_volume:/usr/src/ChinaBack/mediafiles
      - frontend_volume:/usr/src/ChinaBack/frontend
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.prod.db

volumes:
  postgres_data:
  static_volume:
  frontend_volume:
