version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    build: ./ChinaBack
    command: gunicorn ChinaBack.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/ChinaBack/staticfiles
      - media_volume:/usr/src/ChinaBack/mediafiles
    expose:
      - 8000
    env_file:
      - envs/.env.dev
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/ChinaBack/staticfiles
      - media_volume:/usr/src/ChinaBack/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
