# Generated by Django 3.0.1 on 2020-01-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название стажировки')),
                ('time', models.TextField(verbose_name='Когда?')),
                ('place', models.TextField(verbose_name='Где?')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('image1', models.ImageField(blank=True, upload_to='internship_images', verbose_name='Первая картинка')),
                ('image2', models.ImageField(blank=True, upload_to='internship_images', verbose_name='Вторая картинка')),
                ('image3', models.ImageField(blank=True, upload_to='internship_images', verbose_name='Третья картинка')),
                ('image4', models.ImageField(blank=True, upload_to='internship_images', verbose_name='Четвертая картинка')),
                ('start', models.DateField(verbose_name='Дата начала стажировки')),
                ('end', models.DateField(verbose_name='Дата конца стажировки')),
                ('is_active', models.BooleanField(verbose_name='Отображать на сайте?')),
            ],
        ),
    ]
