# Generated by Django 3.0.1 on 2020-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0002_internship_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='internship',
            name='organization',
            field=models.TextField(default='', verbose_name='Организация'),
        ),
    ]
