# Generated by Django 3.0.1 on 2020-01-03 20:14

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости')),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('short_text', models.TextField(verbose_name='Короткий текст новости')),
                ('text', djrichtextfield.models.RichTextField(verbose_name='Длиный текст')),
                ('image', models.ImageField(upload_to='news', verbose_name='Картинка для новости')),
                ('tag', models.CharField(choices=[('pol', 'Политика'), ('eco', 'Экономика'), ('cul', 'Культура'), ('peo', 'Люди')], max_length=3, verbose_name='Тег новости')),
            ],
        ),
    ]
